//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalApp_SM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankHistory
    {
        public string HistoryID { get; set; }
        public string StudentID { get; set; }
        public string RankID { get; set; }
        public string RankDate { get; set; }
    
        public virtual Rank Rank { get; set; }
        public virtual Student Student { get; set; }
    }
}
