//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalApp_SM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFamily
    {
        public string ParentID { get; set; }
        public string StudentID { get; set; }
        public string FatherFirstName { get; set; }
        public string FatherLastName { get; set; }
        public string MotherFirstName { get; set; }
        public string MotherLastName { get; set; }
        public string ParentEmail { get; set; }
        public string ParentPhoneNo { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
