//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalApp_SM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendance
    {
        public string AttendanceID { get; set; }
        public string StudentID { get; set; }
        public string ClassID { get; set; }
        public string AttendanceTakenDate { get; set; }
        public string IsPresent { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
    }
}
